eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      profile: dev
      discovery:
        service-id: configuration
        enabled: true
#feign:
#    hystrix:
#      enabled: true
#阿里云OSS配置
#oss:
#  endpoint: http://oss-cn-shanghai.aliyuncs.com
#  accessKeyId: LTAIg52OToLAqTPF
#  accessKeySecret: oiRdzTjZZcirAWlfl5BHpdyYUidP21
#  bucketName: ctgdev
#  keyPath: urm/